name: Deploy to fly.io

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build Frontend
        run: |
          cd book-frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: book-frontend/build/
  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: book-backend/src/main/resources/static
      - name: Build with maven
        run: mvn -B package --file book-backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: book-backend/target/app.jar
  deploy-fly:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-fly.io
      url: https://mybooklibraryapp.fly.dev/
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: book-backend/target
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy